# Reusable Build Workflow
name: _Build

on:
  workflow_call:

jobs:
  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: ./gradlew buildPlugin

      - name: Get build file name
        run: |
          FILENAME=$(ls ./build/distributions/*.zip)
          echo "filename=${FILENAME}" >> $GITHUB_ENV

      - name: Cache compiled plugin
        uses: actions/cache@v3
        with:
          path: build/distributions/
          key: compiled-plugin-${{ github.sha }}