# Reusable Test Workflow
name: _Test

on:
  workflow_call:

jobs:
  test-ui:
    name: Test UI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            runTests: |
              export DISPLAY=:99.0
              Xvfb -ac :99 -screen 0 1920x1080x24 &
              sleep 10
              ./gradlew test
            reportName: ui-test-fails-report-linux
          - os: windows-latest
            runTests: ./gradlew test
            reportName: ui-test-fails-report-windows
          - os: macos-latest
            runTests: ./gradlew test
            reportName: ui-test-fails-report-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install basic project fixture dependencies
        working-directory: src/test/testData/basic-project
        run: npm i

      - name: Install IDEA license key
        run: |
          mkdir -p ./build/idea-sandbox/config-uiTest
          echo "${{ secrets.JETBRAINS_LICENSE_KEY }}" | base64 --decode > ./build/idea-sandbox/config-uiTest/idea.key

      - name: Run
        run: ${{ matrix.runTests }}

      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.reportName }}
          path: ./build/reports
